version: "3.2"
networks:
  elk:
    driver: bridge
services:
  elasticsearch:
    image: elasticsearch:7.17.5
    container_name: elasticsearch
    restart: always
    networks:
      - elk
    volumes:
      - ./data:/Users/chengang/Desktop/个人项目/docker-image/elastic/search/data
      - ./logs:/Users/chengang/Desktop/个人项目/docker-image/elastic/search/logs
      - ./plugins:/Users/chengang/Desktop/个人项目/docker-image/elastic/search/plugins
      - ./config/elasticsearch.yml:/Users/chengang/Desktop/个人项目/docker-image/elastic/search/config/elasticsearch.yml
    ports:
      - 9200:9200
    environment:
      # 开启内存锁定
      - bootstrap.memory_lock=true
      # 修改jvm内存
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # 指定单节点启动
      - discovery.type=single-node
      - ELASTIC_PASSWORD="123456"
    ulimits:
      # 取消内存相关限制  用于开启内存锁定
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:7.8.0
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      I18N_LOCALE: zh-CN
    networks:
      - elk
  es-head:
    image: mobz/elasticsearch-head:5-alpine
    container_name: es-head
    restart: always
    ports:
      - 9100:9100
    networks:
      - elk

