version: "2.2"
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    restart: always
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - /Users/chengang/docker/kafka/zookeeper:/bitnami/zookeeper
      - /etc/localtime:/etc/localtime:ro
    cpus: '1'
    mem_limit: 500m
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    restart: always
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    volumes:
      - "./kafka/data/:/kafka"
      - /etc/localtime:/etc/localtime:ro
    cpus: '2'
    mem_limit: 2048m
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: always
    ports:
       - "9000:9000"
    environment:
       KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - zookeeper
      - kafka
    cpus: '1'
    mem_limit: 1024m
    container_name: kafdrop
